// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: durable-workflow-runtime/src/test/proto/greet.proto

package com.amannmalik.grpc;

public final class Greet {
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_GreeterApi_HelloRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GreeterApi_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_GreeterApi_HelloReply_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GreeterApi_HelloReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      """

3durable-workflow-runtime/src/test/prot\
o/greet.proto\022
GreeterApi"\034
\014HelloReques\
t\022\014
\004name\030\001 \001(\t"\035

HelloReply\022\017
\007message\
\030\001 \001(\t2I
\007Greeter\022>
\010SayHello\022\030.GreeterA\
pi.HelloRequest\032\026.GreeterApi.HelloReply"\
\000B\027
\023com.amannmalik.grpcP\001b\006proto3"""
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
    internal_static_GreeterApi_HelloRequest_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_GreeterApi_HelloRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_GreeterApi_HelloRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_GreeterApi_HelloReply_descriptor = getDescriptor().getMessageTypes().get(1);
    internal_static_GreeterApi_HelloReply_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_GreeterApi_HelloReply_descriptor,
            new java.lang.String[] {
              "Message",
            });
  }

  private Greet() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  // @@protoc_insertion_point(outer_class_scope)
}
