// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: durable-workflow-runtime/src/test/proto/greet.proto

package com.amannmalik.grpc;

import com.google.protobuf.Descriptors.Descriptor;
import com.google.protobuf.Descriptors.FileDescriptor;
import com.google.protobuf.ExtensionRegistry;
import com.google.protobuf.ExtensionRegistryLite;
import com.google.protobuf.GeneratedMessageV3.FieldAccessorTable;

public final class Greet {
    static final Descriptor
            internal_static_GreeterApi_HelloRequest_descriptor;
    static final FieldAccessorTable
            internal_static_GreeterApi_HelloRequest_fieldAccessorTable;
    static final Descriptor
            internal_static_GreeterApi_HelloReply_descriptor;
    static final FieldAccessorTable
            internal_static_GreeterApi_HelloReply_fieldAccessorTable;
    private static final FileDescriptor descriptor;

    static {
        String[] descriptorData = {
                """

3durable-workflow-runtime/src/test/prot\
o/greet.proto\022
GreeterApi"\034
\014HelloReques\
t\022\014
\004name\030\001 \001(\t"\035

HelloReply\022\017
\007message\
\030\001 \001(\t2I
\007Greeter\022>
\010SayHello\022\030.GreeterA\
pi.HelloRequest\032\026.GreeterApi.HelloReply"\
\000B\027
\023com.amannmalik.grpcP\001b\006proto3"""
        };
        descriptor =
                FileDescriptor.internalBuildGeneratedFileFrom(
                        descriptorData, new FileDescriptor[]{});
        internal_static_GreeterApi_HelloRequest_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_GreeterApi_HelloRequest_fieldAccessorTable =
                new FieldAccessorTable(
                        internal_static_GreeterApi_HelloRequest_descriptor,
                        new String[]{
                                "Name",
                        });
        internal_static_GreeterApi_HelloReply_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_GreeterApi_HelloReply_fieldAccessorTable =
                new FieldAccessorTable(
                        internal_static_GreeterApi_HelloReply_descriptor,
                        new String[]{
                                "Message",
                        });
    }

    private Greet() {
    }

    public static void registerAllExtensions(ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(ExtensionRegistry registry) {
        registerAllExtensions((ExtensionRegistryLite) registry);
    }

    public static FileDescriptor getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
