// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: durable-workflow-runtime/src/test/proto/greet.proto

package com.amannmalik.grpc;

import com.google.protobuf.ByteString;
import com.google.protobuf.MessageOrBuilder;

public interface HelloRequestOrBuilder
        extends
        // @@protoc_insertion_point(interface_extends:GreeterApi.HelloRequest)
        MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    String getName();

    /**
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    ByteString getNameBytes();
}
