// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: durable-workflow-runtime/src/test/proto/greet.proto

package com.amannmalik.grpc;

public interface HelloReplyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:GreeterApi.HelloReply)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     *
     * @return The message.
     */
    java.lang.String getMessage();

    /**
     * <code>string message = 1;</code>
     *
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
    getMessageBytes();
}
