// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: durable-workflow-runtime/src/test/proto/greet.proto

package com.amannmalik.grpc;

public interface HelloRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:GreeterApi.HelloRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
    getNameBytes();
}
